/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizPlayerIndexRouteImport } from './routes/quiz-player/index'
import { Route as QuizBuilderIndexRouteImport } from './routes/quiz-builder/index'
import { Route as QuizBuilderCreateRouteImport } from './routes/quiz-builder/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizPlayerIndexRoute = QuizPlayerIndexRouteImport.update({
  id: '/quiz-player/',
  path: '/quiz-player/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizBuilderIndexRoute = QuizBuilderIndexRouteImport.update({
  id: '/quiz-builder/',
  path: '/quiz-builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizBuilderCreateRoute = QuizBuilderCreateRouteImport.update({
  id: '/quiz-builder/create',
  path: '/quiz-builder/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz-builder/create': typeof QuizBuilderCreateRoute
  '/quiz-builder': typeof QuizBuilderIndexRoute
  '/quiz-player': typeof QuizPlayerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz-builder/create': typeof QuizBuilderCreateRoute
  '/quiz-builder': typeof QuizBuilderIndexRoute
  '/quiz-player': typeof QuizPlayerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz-builder/create': typeof QuizBuilderCreateRoute
  '/quiz-builder/': typeof QuizBuilderIndexRoute
  '/quiz-player/': typeof QuizPlayerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quiz-builder/create' | '/quiz-builder' | '/quiz-player'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quiz-builder/create' | '/quiz-builder' | '/quiz-player'
  id:
    | '__root__'
    | '/'
    | '/quiz-builder/create'
    | '/quiz-builder/'
    | '/quiz-player/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizBuilderCreateRoute: typeof QuizBuilderCreateRoute
  QuizBuilderIndexRoute: typeof QuizBuilderIndexRoute
  QuizPlayerIndexRoute: typeof QuizPlayerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-player/': {
      id: '/quiz-player/'
      path: '/quiz-player'
      fullPath: '/quiz-player'
      preLoaderRoute: typeof QuizPlayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-builder/': {
      id: '/quiz-builder/'
      path: '/quiz-builder'
      fullPath: '/quiz-builder'
      preLoaderRoute: typeof QuizBuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-builder/create': {
      id: '/quiz-builder/create'
      path: '/quiz-builder/create'
      fullPath: '/quiz-builder/create'
      preLoaderRoute: typeof QuizBuilderCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizBuilderCreateRoute: QuizBuilderCreateRoute,
  QuizBuilderIndexRoute: QuizBuilderIndexRoute,
  QuizPlayerIndexRoute: QuizPlayerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
